<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10_clickUsername</name>
   <tag></tag>
   <elementGuidId>eed8d6aa-64e0-4208-a2dc-c369f75b5066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[./text()='Username']/../../div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
