<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12_clickPassword</name>
   <tag></tag>
   <elementGuidId>99a8f129-b5e2-41e1-a06d-3d050fbb57da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[./text()='Password']/../../div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
